name: clang
on:
  push:
    branches: [ master, development]
  pull_request:
    branches: [ master ]

jobs:
  build-clang-linux-stl:
    name: Clang Linux - STL
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y "clang" "lldb" "lld" "clang-format"
        export CC=clang
        export CXX=clang++
        export ASAN_OPTIONS=alloc_dealloc_mismatch=0,detect_leaks=0
        git fetch --tags
        cmake -D BUILD_TESTS=ON -DNO_STL=OFF -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03=OFF ./
        clang --version
        make -j$(nproc)

    - name: Run tests
      run: ./test/etl_tests

  build-clang-linux-no-stl:
    name: Clang Linux - No STL
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y "clang" "lldb" "lld" "clang-format"
        export CC=clang
        export CXX=clang++
        export ASAN_OPTIONS=alloc_dealloc_mismatch=0,detect_leaks=0
        git fetch --tags
        cmake -DBUILD_TESTS=ON -DNO_STL=ON -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03=OFF ./
        clang --version
        make -j$(nproc)
    
    - name: Run tests
      run: ./test/etl_tests

  build-clang-linux-stl-force-cpp03:
    name: Clang Linux - STL - Force C++03
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y "clang" "lldb" "lld" "clang-format"
        export CC=clang
        export CXX=clang++
        export ASAN_OPTIONS=alloc_dealloc_mismatch=0,detect_leaks=0
        git fetch --tags
        cmake -D BUILD_TESTS=ON -DNO_STL=OFF -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03=ON ./
        clang --version
        make -j$(nproc)

    - name: Run tests
      run: ./test/etl_tests

  build-clang-10-osx-stl:
    name: Clang-10 OSX - STL
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export CC=clang
        export CXX=clang++
        export ASAN_OPTIONS=alloc_dealloc_mismatch=0,detect_leaks=0
        git fetch --tags
        cmake -D BUILD_TESTS=ON -DNO_STL=OFF -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03=OFF ./
        clang --version
        make -j$(sysctl -n hw.ncpu)

    - name: Run tests
      run: ./test/etl_tests

  build-clang-10-osx-stl-cpp14:
    name: Clang-10 OSX - STL - CPP14
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          export CC=clang
          export CXX=clang++
          export ASAN_OPTIONS=alloc_dealloc_mismatch=0,detect_leaks=0
          git fetch --tags
          cmake -D BUILD_TESTS=ON -DNO_STL=OFF -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03=OFF -DCMAKE_CXX_STANDARD=14 ./
          clang --version
          make -j$(sysctl -n hw.ncpu)

      - name: Run tests
        run: ./test/etl_tests

  build-clang-10-osx-no-stl:
    name: Clang-10 OSX - No STL
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export CC=clang
        export CXX=clang++
        export ASAN_OPTIONS=alloc_dealloc_mismatch=0,detect_leaks=0
        git fetch --tags
        cmake -D BUILD_TESTS=ON -DNO_STL=ON -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03=OFF ./
        clang --version
        make -j$(sysctl -n hw.ncpu)

    - name: Run tests
      run: ./test/etl_tests

  build-clang-10-osx-no-stl-cpp14:
    name: Clang-10 OSX - No STL - CPP14
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          export CC=clang
          export CXX=clang++
          export ASAN_OPTIONS=alloc_dealloc_mismatch=0,detect_leaks=0
          git fetch --tags
          cmake -D BUILD_TESTS=ON -DNO_STL=ON -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03=OFF -DCMAKE_CXX_STANDARD=14 ./
          clang --version
          make -j$(sysctl -n hw.ncpu)

      - name: Run tests
        run: ./test/etl_tests

  build-clang-10-osx-stl-force-cpp03:
    name: Clang-10 OSX - STL - Force C++03
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export CC=clang
        export CXX=clang++
        export ASAN_OPTIONS=alloc_dealloc_mismatch=0,detect_leaks=0
        git fetch --tags
        cmake -D BUILD_TESTS=ON -DNO_STL=OFF -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03=ON ./
        clang --version
        make -j$(sysctl -n hw.ncpu)

    - name: Run tests
      run: ./test/etl_tests

